### ISSUE TITLE
MainWindowHandle empty (Win 11, 22621.436, Windows Terminal)

### ISSUE THREAD

**Issue by nyanhp** [TobiasPSP/Modules.PsoProgressButton#1]
Unfortunately, on my machine at least the MainWindowHandle is empty in both WinPS and PS7. Oddly enough, using `Get-Process`, the MainWindowHandle is populated.

Steps to Reproduce
```powershell
Set-PsoProgressButtonValue -CurrentValue 50 # error: "TaskbarManager: Valid Window Required"

[Diagnostics.Process]::GetCurrentProcess().MainWindowHandle # on my machine: 0
[Diagnostics.Process]::GetCurrentProcess() -eq $pid # True
(Get-Process -Id $pid).MainWindowHandle # on my machine: IntPtr that would work
```

PSVersionTable:
```output
Name                           Value
----                           -----
PSVersion                      5.1.22621.436
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.436
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by TobiasPSP** [comment]
Wow that’s unexpected. For me it runs well in ISE, powershell.exe and pwsh.exe. Thanks for reporting. When I find the time to dig into the code, can I ask you to do some checks on your side as I can’t repro?

**Comment by TobiasPSP** [comment]
Are you running PS in any special way, i.e. elevated?

**Comment by nyanhp** [comment]
@TobiasPSP you are right, of course. I didn't even try the ISE. After some additional digging, I can pin this issue on the Windows Terminal console host.

This is very easy to reproduce - the MainWindowHandle always seems to be 0 when WInPS/PS are run from within Windows Terminal. My initial observation, that `Get-Process` returned a different result must have been a typo on my end, the property MainWindowHandle is also 0 which makes a lot more sense.

Here are my results, elevated and non-elevated:
- Plain PowerShell and ISE: works very well
- WIndows Terminal, VS Code pwsh, VS Code PS Extension Shell: MainWIndowHandle 0 - Does not work

I'm happy to help troubleshooting, as I have no idea why there would be no handle in the VS Code and Windows Terminal hosts. Initially I thought it may have to do with Terminal being a UWP app, but then why would it happen with VS Code as well?

**Comment by TobiasPSP** [comment]
Well when the consoles run inside wt, do they have taskbar buttons at all? The handle refers to the taskbar button, not the window, I‘d assume. Thx for reporting, this all makes sense now, and I‘ll be adding a note to the project.

**Comment by TobiasPSP** [comment]
Conclusion: the commands require the script to run in a visible window. When the PowerShell window is hidden, i.e. because it is running within Windows Terminal or as a hidden helper window within VSCode, there are no taskbar buttons to access thus the commands fail and return a missing handle. As far as I see, this is expected behavior.
